import { promises as fs } from 'node:fs';
import path from 'node:path';
// Build quoin design tokens from DTCG source into:
//   dist/tokens.css  — CSS custom properties (:root for light, [data-theme="dark"] override)
//   dist/index.js    — ESM object of CSS var() references, e.g. tokens.color.accent.default
//   dist/index.d.ts  — typed literal declaration for the above (autocomplete on token paths)
//
// We drive Style Dictionary programmatically (rather than a declarative config) because we
// produce one combined stylesheet from two separate token sets (light + dark).
import StyleDictionary from 'style-dictionary';

const PREFIX = 'quoin';
const BUILD_PATH = 'dist/';

// Explicit transform list: we deliberately omit `size/rem` so authored dimension strings
// (e.g. "12px") pass through verbatim, and keep `color/css` to normalize hex values.
const TRANSFORMS = ['attribute/cti', 'name/kebab', 'color/css'];

// Only semantic color roles (color.*) are themed; primitives stay in :root only.
const isSemantic = (token) => token.path[0] === 'color';

// --- Custom formats -------------------------------------------------------------------

// Emit an ESM module whose leaves are `var(--quoin-...)` references, nested by token path.
StyleDictionary.registerFormat({
  name: 'javascript/quoin-vars',
  format: ({ dictionary }) => {
    const tree = buildVarTree(dictionary.allTokens);
    return `// AUTO-GENERATED by sd.build.js — do not edit.\nexport const tokens = ${JSON.stringify(tree, null, 2)};\n`;
  },
});

// Emit a matching .d.ts with the full literal shape so consumers get path autocomplete.
StyleDictionary.registerFormat({
  name: 'typescript/quoin-dts',
  format: ({ dictionary }) => {
    const tree = buildVarTree(dictionary.allTokens);
    return `// AUTO-GENERATED by sd.build.js — do not edit.\nexport declare const tokens: {\n${printType(tree, '  ')}\n};\n`;
  },
});

function buildVarTree(tokens) {
  const tree = {};
  for (const token of tokens) {
    let node = tree;
    token.path.forEach((segment, i) => {
      if (i === token.path.length - 1) {
        node[segment] = `var(--${token.name})`;
      } else {
        node[segment] ??= {};
        node = node[segment];
      }
    });
  }
  return tree;
}

function printType(node, indent) {
  return Object.entries(node)
    .map(([key, value]) => {
      const safeKey = /^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key);
      if (typeof value === 'string') {
        return `${indent}readonly ${safeKey}: string;`;
      }
      return `${indent}readonly ${safeKey}: {\n${printType(value, `${indent}  `)}\n${indent}};`;
    })
    .join('\n');
}

// --- Builds ---------------------------------------------------------------------------

// Light: all primitives + light semantics → :root. Also emits the JS/TS var modules.
const light = new StyleDictionary({
  source: ['tokens/primitive/**/*.json', 'tokens/semantic/light.json'],
  usesDtcg: true,
  log: { verbosity: 'silent' },
  platforms: {
    css: {
      transforms: TRANSFORMS,
      prefix: PREFIX,
      buildPath: BUILD_PATH,
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: { selector: ':root', outputReferences: false },
        },
      ],
    },
    js: {
      transforms: TRANSFORMS,
      prefix: PREFIX,
      buildPath: BUILD_PATH,
      files: [
        { destination: 'index.js', format: 'javascript/quoin-vars' },
        { destination: 'index.d.ts', format: 'typescript/quoin-dts' },
      ],
    },
  },
});

// Dark: primitives present so references resolve, but only semantic color roles are output,
// scoped to [data-theme="dark"].
const dark = new StyleDictionary({
  source: ['tokens/primitive/**/*.json', 'tokens/semantic/dark.json'],
  usesDtcg: true,
  log: { verbosity: 'silent' },
  platforms: {
    css: {
      transforms: TRANSFORMS,
      prefix: PREFIX,
      buildPath: BUILD_PATH,
      files: [
        {
          destination: '_dark.css',
          format: 'css/variables',
          filter: isSemantic,
          options: { selector: '[data-theme="dark"]', outputReferences: false },
        },
      ],
    },
  },
});

await light.buildAllPlatforms();
await dark.buildAllPlatforms();

// Concatenate the dark override onto tokens.css, then remove the temp file.
const tokensCssPath = path.join(BUILD_PATH, 'tokens.css');
const darkCssPath = path.join(BUILD_PATH, '_dark.css');
const [lightCss, darkCss] = await Promise.all([
  fs.readFile(tokensCssPath, 'utf8'),
  fs.readFile(darkCssPath, 'utf8'),
]);
// Drop the auto-generated banner comment from the dark partial before appending.
const darkBody = darkCss.replace(/^\/\*\*[\s\S]*?\*\/\s*/, '');
await fs.writeFile(tokensCssPath, `${lightCss}\n${darkBody}`, 'utf8');
await fs.rm(darkCssPath);

console.log('✓ quoin tokens built → dist/tokens.css, dist/index.js, dist/index.d.ts');
