import { promises as fs } from 'node:fs';
import path from 'node:path';
// Build quoin design tokens from DTCG source into:
//   dist/tokens.css  — CSS custom properties (:root for light, [data-theme="dark"] override)
//   dist/index.js    — ESM object of CSS var() references, e.g. tokens.color.accent.default
//   dist/index.d.ts  — typed literal declaration for the above (autocomplete on token paths)
//
// We drive Style Dictionary programmatically (rather than a declarative config) because we
// produce one combined stylesheet from two separate token sets (light + dark).
import StyleDictionary from 'style-dictionary';

const PREFIX = 'quoin';
const BUILD_PATH = 'dist/';

// Also emitted (see below):
//   dist/tokens.json — a flat metadata array (path, cssVar, type, tier, resolved
//                      light `value` + dark `valueDark`, alias `reference`) that
//                      the @jasondaihl/quoin-mcp server reads to answer token queries.

// Explicit transform list: we deliberately omit `size/rem` so authored dimension strings
// (e.g. "12px") pass through verbatim, and keep `color/css` to normalize hex values.
const TRANSFORMS = ['attribute/cti', 'name/kebab', 'color/css'];

// Only semantic color roles (color.*) are themed; primitives stay in :root only.
const isSemantic = (token) => token.path[0] === 'color';

// --- Custom formats -------------------------------------------------------------------

// Emit an ESM module whose leaves are `var(--quoin-...)` references, nested by token path.
StyleDictionary.registerFormat({
  name: 'javascript/quoin-vars',
  format: ({ dictionary }) => {
    const tree = buildVarTree(dictionary.allTokens);
    return `// AUTO-GENERATED by sd.build.js — do not edit.\nexport const tokens = ${JSON.stringify(tree, null, 2)};\n`;
  },
});

// Emit a matching .d.ts with the full literal shape so consumers get path autocomplete.
StyleDictionary.registerFormat({
  name: 'typescript/quoin-dts',
  format: ({ dictionary }) => {
    const tree = buildVarTree(dictionary.allTokens);
    return `// AUTO-GENERATED by sd.build.js — do not edit.\nexport declare const tokens: {\n${printType(tree, '  ')}\n};\n`;
  },
});

// Emit a flat metadata array consumed by @jasondaihl/quoin-mcp. Values are already resolved
// (references substituted) by Style Dictionary; `reference` preserves the authored
// alias (e.g. "{palette.indigo.600}") when the token is an alias.
StyleDictionary.registerFormat({
  name: 'json/quoin-metadata',
  format: ({ dictionary }) => {
    return `${JSON.stringify(buildMetadata(dictionary.allTokens), null, 2)}\n`;
  },
});

function buildMetadata(tokens) {
  return tokens.map((token) => {
    const authored = token.original?.$value;
    const reference = typeof authored === 'string' && authored.includes('{') ? authored : null;
    return {
      path: token.path.join('.'),
      cssVar: `--${token.name}`,
      type: token.$type ?? null,
      tier: isSemantic(token) ? 'semantic' : 'primitive',
      value: token.$value,
      reference,
    };
  });
}

function buildVarTree(tokens) {
  const tree = {};
  for (const token of tokens) {
    let node = tree;
    token.path.forEach((segment, i) => {
      if (i === token.path.length - 1) {
        node[segment] = `var(--${token.name})`;
      } else {
        node[segment] ??= {};
        node = node[segment];
      }
    });
  }
  return tree;
}

function printType(node, indent) {
  return Object.entries(node)
    .map(([key, value]) => {
      const safeKey = /^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key);
      if (typeof value === 'string') {
        return `${indent}readonly ${safeKey}: string;`;
      }
      return `${indent}readonly ${safeKey}: {\n${printType(value, `${indent}  `)}\n${indent}};`;
    })
    .join('\n');
}

// --- Builds ---------------------------------------------------------------------------

// Theming has two orthogonal axes: BRAND (default, ocean, …) and MODE (light, dark).
// The `default` brand is the base: its light set defines every token on :root (primitives
// + semantics) and its dark set overrides the semantic color roles under [data-theme="dark"].
// Every other brand is a thin OVERLAY — it re-declares only the semantic roles it changes,
// scoped to [data-brand="<name>"] (light) and [data-brand="<name>"][data-theme="dark"]. CSS
// cascade/specificity then resolves any brand×mode combination. See docs/adr/0008 and
// docs/adding-a-theme.md. To add a brand: author its override files under
// tokens/semantic/brands/<name>/ and add its name to BRANDS below.
const BASE_BRAND = 'default';
const BRANDS = ['default', 'ocean'];
const MODES = ['light', 'dark'];

// Build one (brand, mode) Style Dictionary layer. The base brand's light build is special:
// it alone emits the primitives and the JS/TS/JSON artifacts (metadata tracks the base brand).
function sdFor(brand, mode) {
  const isBase = brand === BASE_BRAND;
  const isLight = mode === 'light';

  // Selector for this layer: base light → :root; otherwise compose the attribute scopes.
  const brandSel = isBase ? '' : `[data-brand="${brand}"]`;
  const modeSel = isLight ? '' : '[data-theme="dark"]';
  const selector = `${brandSel}${modeSel}` || ':root';

  // Base light emits everything (primitives included); every other layer is semantic-only.
  const semanticOnly = !(isBase && isLight);

  const cssFile = {
    destination: `_${brand}.${mode}.css`,
    format: 'css/variables',
    options: { selector, outputReferences: false },
    ...(semanticOnly ? { filter: isSemantic } : {}),
  };
  const files = [cssFile];

  // Base dark also emits the dark semantic values, merged into tokens.json as `valueDark`.
  if (isBase && !isLight) {
    files.push({
      destination: '_tokens.dark.json',
      format: 'json/quoin-metadata',
      filter: isSemantic,
    });
  }

  const platforms = {
    css: { transforms: TRANSFORMS, prefix: PREFIX, buildPath: BUILD_PATH, files },
  };

  // Base light alone emits the JS/TS var modules and the metadata JSON (base-brand values).
  if (isBase && isLight) {
    platforms.js = {
      transforms: TRANSFORMS,
      prefix: PREFIX,
      buildPath: BUILD_PATH,
      files: [
        { destination: 'index.js', format: 'javascript/quoin-vars' },
        { destination: 'index.d.ts', format: 'typescript/quoin-dts' },
        { destination: 'tokens.json', format: 'json/quoin-metadata' },
      ],
    };
  }

  return new StyleDictionary({
    source: ['tokens/primitive/**/*.json', `tokens/semantic/brands/${brand}/${mode}.json`],
    usesDtcg: true,
    log: { verbosity: 'silent' },
    platforms,
  });
}

// Build each layer to its own temp CSS fragment, collected in cascade order:
// base :root, base dark, then each overlay brand's light then dark.
const fragments = [];
for (const brand of BRANDS) {
  for (const mode of MODES) {
    await sdFor(brand, mode).buildAllPlatforms();
    fragments.push(path.join(BUILD_PATH, `_${brand}.${mode}.css`));
  }
}

// Concatenate the fragments into tokens.css, keeping only the first banner comment.
const BANNER = /^\/\*\*[\s\S]*?\*\/\s*/;
const cssParts = await Promise.all(fragments.map((f) => fs.readFile(f, 'utf8')));
const tokensCssPath = path.join(BUILD_PATH, 'tokens.css');
await fs.writeFile(
  tokensCssPath,
  cssParts.map((css, i) => (i === 0 ? css : css.replace(BANNER, ''))).join('\n'),
  'utf8',
);
await Promise.all(fragments.map((f) => fs.rm(f)));

// Merge dark semantic values into the metadata as `valueDark`, then drop the temp file.
const tokensJsonPath = path.join(BUILD_PATH, 'tokens.json');
const darkJsonPath = path.join(BUILD_PATH, '_tokens.dark.json');
const [lightMeta, darkMeta] = await Promise.all([
  fs.readFile(tokensJsonPath, 'utf8').then(JSON.parse),
  fs.readFile(darkJsonPath, 'utf8').then(JSON.parse),
]);
const darkByPath = new Map(darkMeta.map((t) => [t.path, t.value]));
const merged = lightMeta.map((t) =>
  darkByPath.has(t.path) ? { ...t, valueDark: darkByPath.get(t.path) } : t,
);
await fs.writeFile(tokensJsonPath, `${JSON.stringify(merged, null, 2)}\n`, 'utf8');
await fs.rm(darkJsonPath);

console.log(
  '✓ quoin tokens built → dist/tokens.css, dist/index.js, dist/index.d.ts, dist/tokens.json',
);
